paths:
  temp_dir: ./tmp
  output_dir: ./output
frontend:
  prefer_center: true
  afftdn_nf: -25.0
  denoise: true
  normalize: true
separation:
  backend: fv4
  sr_frontend_hz: 44100
  prefer_center: true
  fv4:
    repo_dir: "C:/srtforge/opt/mel-band-roformer"
    cfg:      "C:/srtforge/models/voc_gabox.yaml"
    ckpt:     "C:/srtforge/models/voc_fv4.ckpt"
    num_overlap: 6
  bandit:
    repo_dir: "/opt/bandit"
    ckpt: "/models/bandit_vocals.ckpt"
    cfg: "/models/bandit_vocals.yaml"
    model_name: "BandIt Vocals V7"
vad:
  noise_db: -33.0
  min_silence: 0.35
  pad: 0.1
chunking:
  max_len: 36.0
  overlap: 1.0
models:
  salm_id: nvidia/canary-qwen-2.5b
  parakeet_id: nvidia/parakeet-tdt-0.6b-v2
salm_context:
  carry_sentences: 2
  max_prompt_tokens: 256
  max_total_tokens: 1024
  max_new_tokens: 256
  keywords_file: null
parakeet:
  enabled: true
  use_gpu: true
combination:
  enable_rover: true
  method: maxconf
alignment:
  use_mfa: false
  acoustic_model: english_mfa
  dict_path: "/path/to/english.dict"
reading:
  max_chars_per_line: 42
  max_lines: 2
  min_duration_s: 1.0
